### ISSUE TITLE
Ability to keep parent nodes open in accordion mode

### ISSUE THREAD

**Issue by jobooker** [tefra/navgoco#18]
If I click on a node, A, in accordin mode and it has children, I expected all of A's children to show, and everything else to hide. If I click A again, it'd be nice to have the option to NOT hide A's children. I am finding that I accidentally click things twice sometimes, and then it collapses the children, so you end up in a state where the "active" node is no longer open. I find this confusing.

But I love the widget so far, thank you!

**Comment by tefra** [comment]
I know it's a little frustrating but by definition that's the accordion mode, only branch of of the menu tree can be open at any time. To make it remember the state of other branches would add a complexity to the code that I am not a fan. 

The accordion mode, right now takes like 7 lines of code...
