### ISSUE TITLE
caretHtml option

### ISSUE THREAD

**Issue by pchaganti** [tefra/navgoco#20]
Is it supposed to over ride the drop-down arrow or just add another icon next to it?

thanks!

**Comment by tefra** [comment]
The default caret html is simply an empty span. The caretHtml option is to add your custom html code inside that empty span.

Note that you might want to remove the default css about the caret:

```
.nav li > a > span {
    float: right;
    font-size: 19px;
    font-weight: bolder;
}

.nav li > a:hover > span {
    color: #fff;
}

.nav li > a > span:after {
    content: '\25be';
}
.nav li.open > a > span:after {
    content: '\25b4';
}
```
