### ISSUE TITLE
Cannot link to URL using function onClickAfter (e, submenu)

### ISSUE THREAD

**Issue by monita76** [tefra/navgoco#23]
Hi there
I'm using navgoco accordion menu on my website.
By 
onClickAfter: function(e, submenu) {
			e.preventDefault();
			$('#hauptnavigation').find('li').removeClass('active');
			var li =  $(this).parent();
			var lis = li.parents('li');
			li.addClass('active');
			lis.addClass('active');
		},
I tried to add an active class to submenu items. Works well, but the <a href> link on the submenu item does not work any more. 
Any idea how I can fix it?
Thanks

**Comment by illuminate3** [comment]
Confirmed.
I just deleted that line. What it does ... sadly, I don't know.

```
		onClickAfter: function(e, submenu) {
			e.preventDefault();
```
```
		onClickAfter: function(e, submenu) {
```

**Comment by tefra** [comment]
The e.preventDefault is used to prevent the normal action of the event, in this case to follow the href.

Not really sure what's the issue, but look resolved ;p
