### ISSUE TITLE
Demo page - link google

### ISSUE THREAD

**Issue by Mesinme** [tefra/navgoco#24]
Hi,

First i want to say, cool menu, like it. 
I have an issue with the demo version. 
I see there is a link to the googlepage but it does not work for me (No browser no mac or pc). 
When i press open in new window it goes but not just clicking like that.
Any solution for that? Or is it just me?

Thanks in advance

**Comment by illuminate3** [comment]
Looks like all the links are broken ...

**Comment by tefra** [comment]
It's a demo page, of course if i am going to disable leaving from it ;p

I have to remove that bit from the demo page.
