### ISSUE TITLE
HREF links not working

### ISSUE THREAD

**Issue by Alejxander** [tefra/navgoco#26]
Hi Tefra, I can`t get this to work, I have a big menu, with 3 subs. the fact is, when I change the <a href="example.html"> the links doesn`t work... I tried with <span> but the sub menus doesn`t work that way... Can i get an example with all the links working? I mean, with menu--submenu1---submenu2 

this is my code: 
<ul id="demo2" class="nav">
    <li><a href="doors.html">Puertas Cortafuego</a>
        <ul>
            <li><a href="example2.html">Metálicas</a>
				<ul>
                  <li class="dentro"><span><a href="bat.html">Batiente 1 y 2 Hojas</a></span></li>
                  <li class="dentro"><a href="http://www.google.com">Corredera 1 Hoja</a></li>
                  <li class="dentro"><a href="example.html">Corredera varias hojas</a></li>
                  <li class="dentro"><a href="#">Enrollable</a></li>
                  <li class="dentro"><a href="#">Guillotina</a></li>
                  <li class="dentro"><a href="#">Acústica</a></li>
                  <li class="dentro"><a href="#">Blindada</a></li>
				</ul>
            </li>
</ul>

**Comment by SinghParamjeet** [comment]
@Alejxander 

It could be because of your initializer, just change it to
$("#demo1").navgoco({
		caretHtml: '',
		accordion: false,
		openClass: 'open',
		save: true,
		cookie: {
			name: 'navgoco',
			expires: false,
			path: '/'
		},
		slide: {
			duration: 400,
			easing: 'swing'
		}
	});

Remove the parameter for adding the active class in the initializer ie

onClickAfter: function(e, submenu) {
			e.preventDefault();
			$('#demo1').find('li').removeClass('active');
			var li =  $(this).parent();
			var lis = li.parents('li');
			li.addClass('active');
			lis.addClass('active');
}

It worked for me. :+1:

**Comment by tefra** [comment]
I have to remove that bit from demo...

Thanks for the people who figured it out and helped others!
