### ISSUE TITLE
how do you expand a section when a user goes to a page in that section?

### ISSUE THREAD

**Issue by tomjohnson1492** [tefra/navgoco#27]
I love this plugin. I implemented it in a theme here [https://github.com/tomjohnson1492/jekyll-doc](https://github.com/tomjohnson1492/jekyll-doc). However, there's one thing I can't figure out. If a user goes to a page in a section that is collapsed, such as by clicking a link (e.g., [http://tomjohnson1492.github.io/jekyll-doc/collections/](http://tomjohnson1492.github.io/jekyll-doc/collections/)), how can I make that section automatically expand? Is there a function I can call to open a specific section?

**Comment by tomjohnson1492** [comment]
I expanded this question with more detail [here](http://stackoverflow.com/questions/28597345/how-can-i-automatically-expand-a-navigation-folder-when-it-contains-a-page-being).

**Comment by CurlyMoo** [comment]
You need to add 'open' to the active element.

**Comment by tefra** [comment]
Awesome theme @tomjohnson1492 thanks for using navgoco.

Thanks @CurlyMoo !
