### ISSUE TITLE
Create a Bower Package

### ISSUE THREAD

**Issue by nithinM** [tefra/navgoco#32]
Hey @tefra,

Thanks for submitting this plugin to the git repository. This was very helpful me to implement sidebar navigation without any issue. This is kind request you to submit this plugin to Bower Package list. If you  can do so it is really help for us to use it. 
And if you never mind I can do that change for you!. Hopping your feedback.

**Comment by codeyash** [comment]
+1 must

**Comment by codeyash** [comment]
@nithinM  Try run

    bower install navgoco

It will work. Someone already published it in bower app dir. Enjoy :)

**Comment by nithinM** [comment]
Hi @codeyash  

I just check in Bower repo http://bower.io/search/?q=navgoco but it not showing any result it. Yes your correct. But I think that bower.json file not according to the bower.json specification, and also it not properly register with bower repo. I already pull request. Thank you for information!!

**Comment by tefra** [comment]
Done

**Comment by nithinM** [comment]
@tefra Thank you!!
