### ISSUE TITLE
how append new item dynamic ? 

### ISSUE THREAD

**Issue by msm2020** [tefra/navgoco#9]
hello, 

I try to add and refresh "reload" list again in't not work fine ?
 added item not open ? 
any help 

thank you

**Comment by msm2020** [comment]
hello @Navigathor  
sorry for late reply ... i just see this comment now .
my solution is remove main linst and rewrite it again then call $("#youMenuId").navgoco() ; again.

**Comment by harikr2006** [comment]
Workaround for reinitialize navgoco.

After destroyed $("#youMenuId").nacgoco('destroy') remove data "$("#youMenuId").removeData()"
then call $("#youMenuId").nacgoco()..
